# VERSION 1.0.0
# AUTHOR: Eddie Santos
# DESCRIPTION: Project 
# BUILD: docker build --rm -t esantos3/my-project:1.0.0 .
# SOURCE: https://github.com/esantos3/airflow-docker

FROM esantos3/airflow-base:1.0.0
MAINTAINER Eddie Santos <eddie.santos.3@gmail.com>

CMD ["python", "my-project.py"]